#!/usr/bin/env python3
"""
Export the 5k dataset as a TypeScript catalog for the app's offline fallback.

Usage:
  python ml/build_embeddings.py          # need dataset first
  python ml/export_catalog.py            # creates audiofit/src/constants/catalog.generated.ts
  python ml/export_catalog.py --limit 200 --out audiofit/src/constants/catalog.generated.ts

Then in recommender.ts you can optionally import GENERATED_CATALOG instead of
DISCOVERY_CATALOG for a richer offline pool (without needing the microservice).

Note: Bundling 5k full embeddings into JS would bloat the app (~5 MB).
This exporter only ships *metadata* (title, artist, genres, bpm, energy, etc.)
for offline lexical scoring via recommender.ts. The vector search stays on the server.
"""
import argparse
import json
import csv
from pathlib import Path

import sys
sys.path.insert(0, str(Path(__file__).parent))
import config

def main():
    p = argparse.ArgumentParser(description="Export catalog for app offline bundle")
    p.add_argument("--in", dest="inp", type=str, default=config.DATASET_CSV)
    p.add_argument("--out", type=str, default="audiofit/src/constants/catalog.generated.ts")
    p.add_argument("--limit", type=int, default=500, help="Max tracks to export (keep bundle small)")
    p.add_argument("--min-popularity", type=int, default=0)
    args = p.parse_args()

    base = Path(__file__).parent.parent  # project root (React Only Project)
    inp = Path(args.inp)
    if not inp.is_absolute():
        # ml/data/... -> resolve from ml/ folder
        inp = Path(__file__).parent / inp
        inp = Path(str(inp).replace("ml/ml/", "ml/"))
    out = Path(args.out)
    if not out.is_absolute():
        out = base / args.out

    if not inp.exists():
        print(f"ERROR: {inp} not found. Run: python ml/extract_dataset.py")
        return

    import pandas as pd
    df = pd.read_csv(inp)
    if "popularity" in df.columns:
        df = df[df["popularity"] >= args.min_popularity]
    df = df.sort_values(by="popularity", ascending=False).head(args.limit)

    rows = []
    for _, r in df.iterrows():
        genres = str(r.get("genres","")).strip()
        genres_list = [g for g in genres.split("|") if g] if genres else []
        rows.append({
            "id": str(r["id"]),
            "title": str(r["title"]).replace("'", "\\'").replace('"', '\\"'),
            "artist": str(r["artist"]).replace("'", "\\'").replace('"', '\\"'),
            "genres": genres_list,
            "bpm": int(r["bpm"]),
            "energy": float(r["energy"]),
            "popularity": float(r.get("popularity",50))/100.0,
            "language": str(r.get("language","english")),
        })

    # Write TS file
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by ml/export_catalog.py — do not edit manually\n")
        f.write(f"// Source: {inp.name}, {len(rows)} tracks (limit {args.limit}), sorted by popularity\n")
        f.write("// To regenerate: python ml/export_catalog.py\n")
        f.write("import { CandidateSong } from './recommender';\n\n")
        f.write(f"export const GENERATED_CATALOG: CandidateSong[] = [\n")
        for r in rows:
            genres_ts = ", ".join(f"'{g}'" for g in r["genres"])
            f.write(f"  {{ id: '{r['id']}', title: '{r['title']}', artist: '{r['artist']}', genres: [{genres_ts}], bpm: {r['bpm']}, energy: {r['energy']}, popularity: {r['popularity']:.2f} }},\n")
        f.write("];\n")

    print(f"[export] wrote {len(rows)} tracks -> {out}")
    print(f"  To use in app: in recommender.ts replace DISCOVERY_CATALOG with GENERATED_CATALOG (or merge them).")

if __name__ == "__main__":
    main()
