// ponytail: plain fetch, no SDK — queue + playlist + search resolver
export interface ResolvedTrack {
  title: string;
  artist: string;
  reason: string;
  id: string | null;
  image: string | null;
  previewUrl: string | null;
  uri: string | null;
}

export async function searchTrack(token: string, title: string, artist: string): Promise<Pick<ResolvedTrack, 'id' | 'image' | 'previewUrl' | 'uri'>> {
  // ponytail: your get_track_id method — q=song_name, fallback to title only for recall
  const songName = `${title} ${artist}`.trim();
  const tryFetch = async (q: string) => {
    const res = await fetch(`https://api.spotify.com/v1/search?q=${encodeURIComponent(q)}&type=track&limit=1`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (!res.ok) return null;
    const data = await res.json();
    return data?.tracks?.items?.[0] ?? null;
  };
  let t = await tryFetch(songName);
  if (!t && songName !== title) t = await tryFetch(title);
  if (!t) return { id: null, image: null, previewUrl: null, uri: null };
  return {
    id: t.id ?? null,
    image: t.album?.images?.[0]?.url ?? null,
    previewUrl: t.preview_url ?? null,
    uri: t.uri ?? (t.id ? `spotify:track:${t.id}` : null),
  };
}

export async function resolveTracks(token: string, songs: { title: string; artist: string; reason: string }[]): Promise<ResolvedTrack[]> {
  const out: ResolvedTrack[] = [];
  for (const s of songs) {
    try {
      const r = await searchTrack(token, s.title, s.artist);
      out.push({ ...s, ...r });
    } catch {
      out.push({ ...s, id: null, image: null, previewUrl: null, uri: null });
    }
  }
  return out;
}

export async function addToQueue(token: string, trackId: string): Promise<void> {
  const res = await fetch(`https://api.spotify.com/v1/me/player/queue?uri=${encodeURIComponent(`spotify:track:${trackId}`)}`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(`${res.status}: ${text.slice(0, 200)}`);
  }
}

export async function createPlaylist(token: string, _userId: string, name: string, trackIds: string[], description = 'Generated by AudioFit AI'): Promise<string> {
  // ponytail: use POST /v1/me/playlists — token identity, no stale userId, fewer 403s
  const createRes = await fetch(`https://api.spotify.com/v1/me/playlists`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name, description, public: false }),
  });
  if (!createRes.ok) {
    const t = await createRes.text().catch(() => '');
    throw new Error(`create playlist ${createRes.status}: ${t.slice(0, 300)}`);
  }
  const pl = await createRes.json();
  const playlistId = pl.id as string;
  if (!playlistId) throw new Error('No playlist id returned');
  if (trackIds.length > 0) {
    const uris = trackIds.map((id) => `spotify:track:${id}`);
    // Spotify allows max 100 per request
    for (let i = 0; i < uris.length; i += 100) {
      const chunk = uris.slice(i, i + 100);
      const addRes = await fetch(`https://api.spotify.com/v1/playlists/${encodeURIComponent(playlistId)}/items`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ uris: chunk }),
      });
      if (!addRes.ok) {
        const t = await addRes.text().catch(() => '');
        throw new Error(`add tracks ${addRes.status}: ${t.slice(0, 300)}`);
      }
    }
  }
  return playlistId;
}
