# Auto-generated by ml/discover_playlists.py — copy into ml/config.py
# Generated 2026-08-26T17:02:31Z | market=IN
#
ENGLISH_WORKOUT_PLAYLISTS = [
    "0xF0eHm3eguBqBvgVyQ3UB",  # GYM PHONK 2026 😈 AGGRESSIVE WORKOUT PHONK MUSIC — 1804040 followers, 0 tracks (via 'gym workout')
    "2SM6rniZl84fEyMCB5KMQB",  # WORKOUT PLAYLIST 2026 — 715949 followers, 0 tracks (via 'workout')
    "3U7mEmGXnG3RJ1lrC2Jhvz",  # GYM SONGS🎀 (for girlies) 2026 — 462539 followers, 0 tracks (via 'cardio workout')
    "44imBReuLDHuIP0j4UmCtm",  # BEAST MODE - Motivation for sports GYM and bodybuilding — 330126 followers, 0 tracks (via 'beast mode workout')
    "5MLyX3xiNllq052FsL47Ga",  # Jogging Music 2026🔥🍑  — 311886 followers, 0 tracks (via 'running workout')
    "7DD7riEgqIZVWzlsd3aNn0",  # GYM RATS 💪WORKOUT AGO 26 | TikTok Top 50 viral 100% Full AURA  — 294319 followers, 0 tracks (via 'beast mode workout')
    "45oqmL3silSTKWTBPahpat",  # MOTIVATION SONGS OF 2026 | BEST SONGS TO PUSH YOUR LIMITS ❌❌📢 — 260500 followers, 0 tracks (via 'gym motivation')
    "280hYAs0wM3CswUTZDVBif",  # No Excuses - Motivation Songs 2026 — 238574 followers, 0 tracks (via 'gym motivation')
    "2DgJ11Y3E9rOS97bgaUwLH",  # CARDIO MUSIC HITS 2026 🔥🍑 — 192257 followers, 0 tracks (via 'cardio workout')
    "2joAU7ngDpwRwH2YPJc4z9",  # EGO MODE ☠️  Scroll to latest 🗿 — 153989 followers, 0 tracks (via 'gym motivation')
    "1h3UACACM9GM9ju7ifeQpf",  # WORKOUT REMIX 2026  💪🏻 GYM WORKOUT 🍑 GYM MOTIVATION 🏃‍♀️WORKOUT MUSIC🏋️‍♂️GYM MUSIC  2026 🎧FITNESS GYM HITS  — 144620 followers, 0 tracks (via 'beast mode workout')
    "1VU91WcVhly4DClcCJB0AE",  # Gym workout Hindi songs — 98537 followers, 0 tracks (via 'gym workout')
    "1LIowjORrNqFFyXYqK0JvE",  # PUNJABI GYM HITS 🔥 | WORKOUT PUMP SONGS | NEW PUNJABI ATTITUDE SONGS 2025  — 75399 followers, 0 tracks (via 'gym workout')
    "3X393B14lthT2jdYmC4TZA",  # Top 100 Workout Songs In The World — 74048 followers, 0 tracks (via 'running workout')
    "6r2bgOL9MUnCDGabTnGGwv",  # GYM Hindi Playlist 🦍 — 65120 followers, 0 tracks (via 'workout')
    "5ByeCHKf2JeN2lssfsXqwD",  # Best Gym Workout English Songs💪 — 55528 followers, 0 tracks (via 'gym workout')
    "5DKd4inxaYKy18YSzNInny",  # Zumba Dance Workout 2026 | Latino Fitness Beats & Songs — 49582 followers, 0 tracks (via 'fitness workout')
    "4VWF0TcCYet7z1RpgLjAaY",  # Gym Motivation Songs tamil | Power Hits for Workout & Fitness | Fight mood — 45416 followers, 0 tracks (via 'workout')
    "1t4sF8NCuaELKkpXoSNYKu",  # Trending Mass BGMs 2026 🔥| Goosebumps & GYM Workout 2026 💥 — 36654 followers, 0 tracks (via 'workout')
    "2faxw54KX2Y6XvPHkSUcWo",  # Rap & Hip Hop for gym WORKOUT MOTIVATION 🔥 beast mode training agressive bodybuilding hard extreme — 25480 followers, 0 tracks (via 'fitness workout')
]

HINDI_WORKOUT_PLAYLISTS = [
    "7zNvXEjgmE1110slXAuZie",  # Best Motivational Hindi songs — 259372 followers, 0 tracks (via 'hindi workout')
    "7bPv5uVjGF1oZ6YQAqvEvM",  # BEST WORKOUT SONGS FOR 2024 💪😎 (English & Hindi) — 73081 followers, 0 tracks (via 'hindi workout')
    "5aIBPqncw4027KuElibWRv",  # GYM Hindi x ENGLISH — 55930 followers, 0 tracks (via 'hindi gym')
    "7oVarqwTiJ75pMjsYKDCFl",  # HINDI WORKOUT SONGS — 27759 followers, 0 tracks (via 'hindi workout')
    "6wji2e4EATQ18zfujiuhPZ",  # BOLLYWOOD (GYM VERSION) — 26869 followers, 0 tracks (via 'bollywood workout')
    "71kFbq1Co2aw1ujCQHdeTg",  # 💪🇮🇳INDIAN WORKOUT SONGS🏋️ — 24218 followers, 0 tracks (via 'desi workout')
    "1RY4hHMzlWRqNVyGm0kW7H",  # The Best Bhangra Mix 2026! — 23717 followers, 0 tracks (via 'bhangra workout')
    "3fe6tXjp8x87sMLffEie2Q",  # Powerful Gym Workout Motivation - Hindi x English  2026 — 21161 followers, 0 tracks (via 'hindi workout')
    "3LEBr6x1S9hiNo8Ggk26JW",  # MOTIVATIONAL PUNJABI SONGS — 18210 followers, 0 tracks (via 'punjabi gym')
    "1YJ3Wk21B7vZrSuO3jo5ij",  # GYM MOTIVATIONAL HINDI SONGS — 17035 followers, 0 tracks (via 'hindi gym')
    "60VTe7XgOb4EWmlhTtU9IQ",  # Punjabi Bhangra Songs 🔥 — 16287 followers, 0 tracks (via 'bhangra workout')
    "2uoWuSk4K6YXhCEyKDNuKl",  # Punjabi Gym Songs – Workout Hits — 16248 followers, 0 tracks (via 'punjabi workout')
]

ALL_PLAYLISTS = ENGLISH_WORKOUT_PLAYLISTS + HINDI_WORKOUT_PLAYLISTS
