// Auto-generated by ml/export_catalog.py — do not edit manually
// Source: audiofit_dataset.csv, 20 tracks (limit 50), sorted by popularity
// To regenerate: python ml/export_catalog.py
import { CandidateSong } from './recommender';

export const GENERATED_CATALOG: CandidateSong[] = [
  { id: 'demo019', title: 'Demo Track 19', artist: 'Artist 4', genres: ['hip hop', 'rap'], bpm: 133, energy: 0.9, popularity: 0.89 },
  { id: 'demo018', title: 'Demo Track 18', artist: 'Artist 3', genres: ['pop', 'dance'], bpm: 126, energy: 0.8, popularity: 0.88 },
  { id: 'demo017', title: 'Demo Track 17', artist: 'Artist 2', genres: ['hip hop', 'rap'], bpm: 119, energy: 0.7, popularity: 0.87 },
  { id: 'demo016', title: 'Demo Track 16', artist: 'Artist 1', genres: ['pop', 'dance'], bpm: 112, energy: 0.6, popularity: 0.86 },
  { id: 'demo015', title: 'Demo Track 15', artist: 'Artist 0', genres: ['hip hop', 'rap'], bpm: 105, energy: 0.5, popularity: 0.85 },
  { id: 'demo014', title: 'Demo Track 14', artist: 'Artist 4', genres: ['pop', 'dance'], bpm: 98, energy: 0.9, popularity: 0.84 },
  { id: 'demo013', title: 'Demo Track 13', artist: 'Artist 3', genres: ['hip hop', 'rap'], bpm: 91, energy: 0.8, popularity: 0.83 },
  { id: 'demo012', title: 'Demo Track 12', artist: 'Artist 2', genres: ['pop', 'dance'], bpm: 174, energy: 0.7, popularity: 0.82 },
  { id: 'demo011', title: 'Demo Track 11', artist: 'Artist 1', genres: ['hip hop', 'rap'], bpm: 167, energy: 0.6, popularity: 0.81 },
  { id: 'demo010', title: 'Demo Track 10', artist: 'Artist 0', genres: ['pop', 'dance'], bpm: 160, energy: 0.5, popularity: 0.80 },
  { id: 'demo009', title: 'Demo Track 9', artist: 'Artist 4', genres: ['hip hop', 'rap'], bpm: 153, energy: 0.9, popularity: 0.79 },
  { id: 'demo008', title: 'Demo Track 8', artist: 'Artist 3', genres: ['pop', 'dance'], bpm: 146, energy: 0.8, popularity: 0.78 },
  { id: 'demo007', title: 'Demo Track 7', artist: 'Artist 2', genres: ['hip hop', 'rap'], bpm: 139, energy: 0.7, popularity: 0.77 },
  { id: 'demo006', title: 'Demo Track 6', artist: 'Artist 1', genres: ['pop', 'dance'], bpm: 132, energy: 0.6, popularity: 0.76 },
  { id: 'demo005', title: 'Demo Track 5', artist: 'Artist 0', genres: ['hip hop', 'rap'], bpm: 125, energy: 0.5, popularity: 0.75 },
  { id: 'demo004', title: 'Demo Track 4', artist: 'Artist 4', genres: ['pop', 'dance'], bpm: 118, energy: 0.9, popularity: 0.74 },
  { id: 'demo003', title: 'Demo Track 3', artist: 'Artist 3', genres: ['hip hop', 'rap'], bpm: 111, energy: 0.8, popularity: 0.73 },
  { id: 'demo002', title: 'Demo Track 2', artist: 'Artist 2', genres: ['pop', 'dance'], bpm: 104, energy: 0.7, popularity: 0.72 },
  { id: 'demo001', title: 'Demo Track 1', artist: 'Artist 1', genres: ['hip hop', 'rap'], bpm: 97, energy: 0.6, popularity: 0.71 },
  { id: 'demo000', title: 'Demo Track 0', artist: 'Artist 0', genres: ['pop', 'dance'], bpm: 90, energy: 0.5, popularity: 0.70 },
];
